services:
  prometheus:
    user: "1000:1000"
    image: prom/prometheus:latest
    command: ["--config.file=/prometheus-config/prometheus.yml"]
    volumes:
      - ./prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090
  
  app:
    image: 06c8c74ce594
    ports:
      - 3000:3000

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100 
  
  grafana:
    user: "0"
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 2000:3000
    depends_on: 
      - prometheus
